/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _CALCULAR_H_RPCGEN
#define _CALCULAR_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif


struct values {
	int a;
	int b;
	char op;
};
typedef struct values values;

#define calcular 9999999
#define UNO 1

#if defined(__STDC__) || defined(__cplusplus)
#define sumar 1
extern  int * sumar_1(values *, CLIENT *);
extern  int * sumar_1_svc(values *, struct svc_req *);
#define restar 2
extern  int * restar_1(values *, CLIENT *);
extern  int * restar_1_svc(values *, struct svc_req *);
#define multiplicar 3
extern  int * multiplicar_1(values *, CLIENT *);
extern  int * multiplicar_1_svc(values *, struct svc_req *);
extern int calcular_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define sumar 1
extern  int * sumar_1();
extern  int * sumar_1_svc();
#define restar 2
extern  int * restar_1();
extern  int * restar_1_svc();
#define multiplicar 3
extern  int * multiplicar_1();
extern  int * multiplicar_1_svc();
extern int calcular_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_values (XDR *, values*);

#else /* K&R C */
extern bool_t xdr_values ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_CALCULAR_H_RPCGEN */
