/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "calcular.h"

bool_t
xdr_values (XDR *xdrs, values *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->a))
		 return FALSE;
	 if (!xdr_int (xdrs, &objp->b))
		 return FALSE;
	 if (!xdr_char (xdrs, &objp->op))
		 return FALSE;
	return TRUE;
}
